package com.zpj.sys.entity;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.zpj.common.UUIDGenerator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "sys_userinfo")
@ApiModel(value = "用户表", description = "用户信息表")
public class User implements java.io.Serializable {
	
	@ApiModelProperty(value = "主键",name="id", required = true)
	private String id= UUIDGenerator.generatePk("user");
	@ApiModelProperty(value = "手机号码",name="phone", required =  false)
	private String phone;
	@ApiModelProperty(value = "微信openid",name="name", required =  false)
	private String wxid;
	@ApiModelProperty(value = "微信昵称",name="wxnickname", required =  false)
	private String wxnickname;
	@ApiModelProperty(value = "最后一次登陆时间",name="lastLoginTime", required =  false)
	private Date lastLoginTime;
	@ApiModelProperty(value = "更新时间",name="updateTime", required =  false)
	private Date updateTime;
	@ApiModelProperty(value = "会员等级表,主键id",name="levelId", required =  false)
	private String levelId;
	@ApiModelProperty(value = "会员等级0,1,2，3,4",name="levelId", required =  false)
	private int level;
	@ApiModelProperty(value = "物流调用接口次数",name="levelId", required =  false)
	private int maxtime;

	@ApiModelProperty(value = "会员开始时间",name="levelId", required =  false)
	private Date startTime;
	@ApiModelProperty(value = "会员结束时间",name="levelId", required =  false)
	private Date endTime;
	@ApiModelProperty(value = "是否过期，0未过期，1已过期",name="levelId", required =  false)
	private String isExpire;


	
	@ApiModelProperty(value = "token",name="token", required =  false)
	private String token;

	@Id
	@Column(name = "id", unique = true, nullable = false ,length=36)
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getWxid() {
		return wxid;
	}
	public void setWxid(String wxid) {
		this.wxid = wxid;
	}
	public String getWxnickname() {
		return wxnickname;
	}
	public void setWxnickname(String wxnickname) {
		this.wxnickname = wxnickname;
	}
	public Date getLastLoginTime() {
		return lastLoginTime;
	}
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
	public Date getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	
	
	
	public String getLevelId() {
		return levelId;
	}
	public void setLevelId(String levelId) {
		this.levelId = levelId;
	}
	@Transient
	public String getToken() {
		return token;
	}
	public void setToken(String token) {
		this.token = token;
	}


	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getMaxtime() {
		return maxtime;
	}

	public void setMaxtime(int maxtime) {
		this.maxtime = maxtime;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getIsExpire() {
		return isExpire;
	}

	public void setIsExpire(String isExpire) {
		this.isExpire = isExpire;
	}

	@Override
	public String toString() {
		StringBuffer sb=new StringBuffer(300);
		return sb.append("id:"+this.id+",phone:"+this.phone+",wxid:"+this.wxid+",wxnickname:"+this.wxnickname+",lastLoginTime:"+this.lastLoginTime+",levelId:"+this.getLevelId()).toString();
	}

}
